version: '2'
services:
  dynamodb-dev:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - backend-dev

  dynamodb-test:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - backend-test

  hangman-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend-dev
    command: ["java", "-jar", "/app.jar", "autosetupdb"]
networks:
  backend-dev:
  backend-test: